insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (1, 'Medico', 'Other plastic operations on tendon', true);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (2, 'Dentista', 'Transfusion of packed cells', false);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (3, 'Enfermera', 'Removal of tube from large intestine or appendix', true);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (4, 'Quimico farmacia', 'Plastic operation on hand with graft of muscle or fascia', false);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (5, 'TENS', 'Total nasal reconstruction', false);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (6, 'TONS', 'Pulmonary scan', false);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (7, 'Director', 'Other excision of common duct', false);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (8, 'Asistente', 'Bronchial dilation', true);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (9, 'Supervisor', 'Removal of lesion of eyelid, not otherwise specified', false);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (10, 'Administrador', 'Psychoanalysis', false);
