insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (1, 'Paddock Laboratories, LLC', false);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (2, 'Wal-Mart Stores Inc', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (3, 'TOPCO ASSOCIATES LLC', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (4, 'AbbVie Inc.', false);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (5, 'Aidarex Pharmaceuticals LLC', false);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (6, 'HyVee Inc', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (7, 'Unit Dose Services', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (8, 'A-S Medication Solutions LLC', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (9, 'Nelco Laboratories, Inc.', false);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (10, 'Upsher-Smith Laboratories, Inc.', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (11, 'CVS PHARMACY', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (12, 'Preferred Pharmaceuticals, Inc.', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (13, 'McNeil Consumer Pharmaceuticals Co.', false);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (14, 'Golden State Medical Supply, Inc.', false);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (15, 'A-S Medication Solutions LLC', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (16, 'PD-Rx Pharmaceuticals, Inc.', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (17, 'Bryant Ranch Prepack', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (18, 'Coria Laboratories', false);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (19, 'Wal-Mart Stores Inc', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (20, 'Antigen Laboratories, Inc.', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (21, 'Trigen Laboratories, Inc.', false);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (22, 'DOLGENCORP INC', false);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (23, 'Dukal Corporation', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (24, 'Golden State Medical Supply, Inc.', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (25, 'REMEDYREPACK INC.', false);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (26, 'LLORENS PHARMACEUTICALS INTERNATIONAL DIVISION', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (27, 'ALILY (ZHANGZHOU) BATH PRODUCTS LTD.', true);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (28, 'L''Oreal USA Products Inc', false);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (29, 'Antigen Laboratories, Inc.', false);
insert into TBL_LABORATORIO (IdLaboratorio, NombreLaboratorio, ActivoLaboratorio) values (30, 'Home Health Depot', false);
