insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (1, 'Angelmo', '93 Pennsylvania Place', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (2, 'Puerto Montt',  '2 Lukken Trail', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (3, 'Mirasol',  '87 Sherman Park', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (4, 'Chamiza', '21 Annamark Point', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (5, 'Piedra azul',  '11178 Sommers Drive', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (6, 'Pargua', '15389 Vernon Crossing', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (7, 'Alerce','4353 Dayton Place', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (8, 'Chaica',  '6332 Merchant Avenue', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (9, 'Chinquihue', '75 Southridge Court', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (10, 'Valdivia','2 Mandrake Terrace', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (11, 'Coronel', '62488 Rutledge Road', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (12, 'Santiago', '194 Walton Way', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (13, 'Valparaiso', '583 Warbler Parkway', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (14, 'arica',  '22723 Loomis Center', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (15, 'Antofagasta', '87 Northview Road', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (16, 'Maullin', '8 Golf View Lane', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (17, 'Chiloe', '4794 Waubesa Center', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (18, 'Castro', '992 Rigney Center', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (19, 'Puerta sur', '207 New Castle Court', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, ActivoCesfam) values (20, 'Calbuco','48 Merchant Crossing', false);
