insert into TBL_COMUNA (IdComuna, NombreComuna, ActivoComuna) values (1, 'Lago dos Rodrigues', true);
insert into TBL_COMUNA (IdComuna, NombreComuna, ActivoComuna) values (2, 'LLanquihue', true);
insert into TBL_COMUNA (IdComuna, NombreComuna, ActivoComuna) values (3, 'Valparaiso', true);
insert into TBL_COMUNA (IdComuna, NombreComuna, ActivoComuna) values (4, 'frutillar', false);
insert into TBL_COMUNA (IdComuna, NombreComuna, ActivoComuna) values (5, 'isla grande', false);
insert into TBL_COMUNA (IdComuna, NombreComuna, ActivoComuna) values (6, 'Saint-Germain-en-Laye', false);
insert into TBL_COMUNA (IdComuna, NombreComuna, ActivoComuna) values (7, 'Dongting', false);
insert into TBL_COMUNA (IdComuna, NombreComuna, ActivoComuna) values (8, 'Wiśniewo', false);
insert into TBL_COMUNA (IdComuna, NombreComuna, ActivoComuna) values (9, 'Jangkungkusumo', true);
insert into TBL_COMUNA (IdComuna, NombreComuna, ActivoComuna) values (10, 'Horqueta', false);
