insert into TBL_CIUDAD (IdCiudad, NombreCiudad, ActivoCiudad) values (1, 'Valdivia', false);
insert into TBL_CIUDAD (IdCiudad, NombreCiudad, ActivoCiudad) values (2, 'Chonchi', false);
insert into TBL_CIUDAD (IdCiudad, NombreCiudad, ActivoCiudad) values (3, 'Muermo', false);
insert into TBL_CIUDAD (IdCiudad, NombreCiudad, ActivoCiudad) values (4, 'Puerto Montt', false);
insert into TBL_CIUDAD (IdCiudad, NombreCiudad, ActivoCiudad) values (5, 'Claroscuro', false);
insert into TBL_CIUDAD (IdCiudad, NombreCiudad, ActivoCiudad) values (6, 'Hospital', false);
insert into TBL_CIUDAD (IdCiudad, NombreCiudad, ActivoCiudad) values (7, 'Vallenar', true);
insert into TBL_CIUDAD (IdCiudad, NombreCiudad, ActivoCiudad) values (8, 'Chamiza', true);
insert into TBL_CIUDAD (IdCiudad, NombreCiudad, ActivoCiudad) values (9, 'Piedra azul', false);
insert into TBL_CIUDAD (IdCiudad, NombreCiudad, ActivoCiudad) values (10, 'Valparaiso', false);
