insert into TBL_REGION (IdRegion, NombreRegion, ActivoRegion) values (1, 'Arica', true);
insert into TBL_REGION (IdRegion, NombreRegion, ActivoRegion) values (2, 'Iquique', true);
insert into TBL_REGION (IdRegion, NombreRegion, ActivoRegion) values (3, 'Antofagasta', false);
insert into TBL_REGION (IdRegion, NombreRegion, ActivoRegion) values (4, 'Puerto Montt', false);
insert into TBL_REGION (IdRegion, NombreRegion, ActivoRegion) values (5, 'Chiloe', true);
insert into TBL_REGION (IdRegion, NombreRegion, ActivoRegion) values (6, 'Valdivia', true);
insert into TBL_REGION (IdRegion, NombreRegion, ActivoRegion) values (7, 'Santiago', true);
insert into TBL_REGION (IdRegion, NombreRegion, ActivoRegion) values (8, 'Valparaiso', true);
insert into TBL_REGION (IdRegion, NombreRegion, ActivoRegion) values (9, 'Concepcion', false);
insert into TBL_REGION (IdRegion, NombreRegion, ActivoRegion) values (10, 'Talca', false);
