insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (1, 'Gil', 'Filippi', '93 Pennsylvania Place', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (2, 'Clemmie', 'Anstis', '2 Lukken Trail', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (3, 'Moe', 'Deluca', '87 Sherman Park', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (4, 'Timmie', 'Gayter', '21 Annamark Point', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (5, 'Bink', 'Wippermann', '11178 Sommers Drive', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (6, 'Armin', 'Westoll', '15389 Vernon Crossing', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (7, 'Alano', 'Muselli', '4353 Dayton Place', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (8, 'Clark', 'Fransemai', '6332 Merchant Avenue', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (9, 'Zerk', 'Klessmann', '75 Southridge Court', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (10, 'Arch', 'Kett', '2 Mandrake Terrace', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (11, 'Zachery', 'Roskelly', '62488 Rutledge Road', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (12, 'Dean', 'Gooderick', '194 Walton Way', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (13, 'Demetris', 'McIlveen', '583 Warbler Parkway', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (14, 'Cornell', 'Linkleter', '22723 Loomis Center', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (15, 'Allie', 'Daily', '87 Northview Road', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (16, 'Randal', 'Killford', '8 Golf View Lane', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (17, 'Hamlin', 'McLanachan', '4794 Waubesa Center', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (18, 'Huntington', 'Moxsom', '992 Rigney Center', false);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (19, 'Peyter', 'Dioniso', '207 New Castle Court', true);
insert into TBL_CESFAM (IdCesfam, NombreCesfam, DireccionCesfam, DireccionUsuarioCesfam, ActivoCesfam) values (20, 'Addie', 'Tremblot', '48 Merchant Crossing', false);
