insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (1, 'China', true);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (2, 'Philippines', true);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (3, 'Indonesia', true);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (4, 'Philippines', true);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (5, 'South Africa', false);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (6, 'China', true);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (7, 'Belarus', true);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (8, 'Peru', false);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (9, 'Portugal', false);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (10, 'Colombia', false);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (11, 'United States', true);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (12, 'Poland', true);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (13, 'Libya', true);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (14, 'Mongolia', true);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (15, 'Russia', false);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (16, 'Serbia', false);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (17, 'France', false);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (18, 'Poland', true);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (19, 'China', true);
insert into TBL_PAIS (IdPais, NombrePais, ActivoPais) values (20, 'China', false);
