insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (1, 'Construction Worker', 'Other plastic operations on tendon', true);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (2, 'Construction Worker', 'Transfusion of packed cells', false);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (3, 'Construction Expeditor', 'Removal of tube from large intestine or appendix', true);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (4, 'Architect', 'Plastic operation on hand with graft of muscle or fascia', false);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (5, 'Estimator', 'Total nasal reconstruction', false);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (6, 'Construction Expeditor', 'Pulmonary scan', false);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (7, 'Construction Expeditor', 'Other excision of common duct', false);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (8, 'Surveyor', 'Bronchial dilation', true);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (9, 'Supervisor', 'Removal of lesion of eyelid, not otherwise specified', false);
insert into TBL_ROL (IdRoles, NombreRol, DescripcionRol, ActivoRol) values (10, 'Construction Worker', 'Psychoanalysis', false);
