insert into TBL_PROGRAMA (IdPrograma, NombrePrograma, DescripcionPrograma, ActivoPrograma) values (1, 'Surveyor', 'Removal of prosthetic device from bile duct', true);
insert into TBL_PROGRAMA (IdPrograma, NombrePrograma, DescripcionPrograma, ActivoPrograma) values (2, 'Engineer', 'Insertion of other spinal devices', true);
insert into TBL_PROGRAMA (IdPrograma, NombrePrograma, DescripcionPrograma, ActivoPrograma) values (3, 'Construction Expeditor', 'Laparoscopic pull-through resection of rectum', true);
insert into TBL_PROGRAMA (IdPrograma, NombrePrograma, DescripcionPrograma, ActivoPrograma) values (4, 'Construction Foreman', 'Combined alcohol and drug detoxification', false);
insert into TBL_PROGRAMA (IdPrograma, NombrePrograma, DescripcionPrograma, ActivoPrograma) values (5, 'Estimator', 'Obliteration of vaginal vault', false);
insert into TBL_PROGRAMA (IdPrograma, NombrePrograma, DescripcionPrograma, ActivoPrograma) values (6, 'Architect', 'Removal of intraluminal foreign body from trachea and bronchus without incision', true);
insert into TBL_PROGRAMA (IdPrograma, NombrePrograma, DescripcionPrograma, ActivoPrograma) values (7, 'Construction Expeditor', 'Removal of dental packing', true);
insert into TBL_PROGRAMA (IdPrograma, NombrePrograma, DescripcionPrograma, ActivoPrograma) values (8, 'Subcontractor', 'Destruction of chorioretinal lesion by radiation therapy', false);
insert into TBL_PROGRAMA (IdPrograma, NombrePrograma, DescripcionPrograma, ActivoPrograma) values (9, 'Electrician', 'Other surgical occlusion of vessels, other vessels of head and neck', false);
insert into TBL_PROGRAMA (IdPrograma, NombrePrograma, DescripcionPrograma, ActivoPrograma) values (10, 'Electrician', 'Diagnostic ultrasound of urinary system', false);
